config/routes.rb
Xander::Application.routes.draw do

  get '/' => 'frontpage#index'
  root :to => 'frontpage#index'

  # login
  get '/login' => 'sessions#index'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  # admin
  get '/admin' => 'admin#index'
  post '/blog' => 'admin#update'

  get '/title/new' => 'admin#title_new'
  post '/title/new' => 'admin#title_create'

  get '/post/:id' => 'admin#post_show'
  get '/post/new' => 'admin#post_new'
  post '/post/new' => 'admin#post_create'

  get '/post/:id/edit' => 'admin#post_edit'

  # needs post udpate
  # needs post delete

  # create new user
  get '/create_new_admin' => 'users#new'
  post '/create_new_admin' => 'users#create'

  # needs to delete music routes and AWS support
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id       :integer          not null, primary key
#  body     :text             not null
#  title_id :integer
#  order    :integer          default(100), not null
#  visible  :boolean          default(TRUE), not null
#  deleted  :boolean          default(FALSE), not null
#

class Post < ActiveRecord::Base
  attr_accessible :title_id,
                  :body,
                  :order,
                  :visible,
                  :deleted

  scope :deleted,     -> { where(:deleted => true) }
  scope :undeleted,   -> { where(:deleted => false) }

  scope :active,      -> { undeleted.where(:visible => true) }
  scope :inactive,    -> { undeleted.where(:visible => false) }

  scope :published,   -> { active.where(:visible => true) }
  scope :unpublished, -> { active.where(:visible => false) }

  belongs_to :title

end

app/models/title.rb
# == Schema Information
#
# Table name: titles
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  order      :integer          default(100), not null
#  visible    :boolean          default(TRUE), not null
#  deleted    :boolean          default(FALSE), not null
#

class Title < ActiveRecord::Base
  attr_accessible :name,
                  :order,
                  :visible,
                  :deleted

  scope :deleted,     -> { where(:deleted => true) }
  scope :undeleted,   -> { where(:deleted => false) }

  scope :active,      -> { undeleted.where(:visible => true) }
  scope :inactive,    -> { undeleted.where(:visible => false) }

  scope :published,   -> { active.where(:visible => true) }
  scope :unpublished, -> { active.where(:visible => false) }

  has_many :posts

  validates :name, presence: true
  validates :order, presence: true
  validates :order, numericality: true

  def published_posts
    self.posts.published
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id            :integer          not null, primary key
#  username      :string(255)      not null
#  password_hash :string(255)
#  email_address :string(255)      not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  uuid          :string(255)
#  superuser     :boolean          default(FALSE), not null
#  active        :boolean          default(FALSE), not null
#

require 'bcrypt'

class User < ActiveRecord::Base
  include BCrypt

  before_save :create_uuid

  attr_accessible :password,
                  :username,
                  :encrypted_password,
                  :password_hash,
                  :login_token,
                  :email_address,
                  :uuid,
                  :superuser,
                  :active
  attr_reader     :password
=begin
  validate :password_not_blank
=end
  validate :username_not_blank
  validate :username_is_not_reserved

  def password_not_blank
    return if self.password.nil?

    if self.password.blank?
      errors.add(:password, "Password can not be blank")
    end
  end

  def username_is_not_reserved
    return unless %w[ root superuser admin webmaster justworks customersupport sysop support ].include?(self.username)
    errors.add(:username, "is invalid")
  end

  def username_not_blank
    return if self.username.nil?

    if self.username.blank?
      errors.add(:username, "Usernname can not be blank")
    end
  end

  def password
    @password ||= Password.new(password_hash)
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end

  def create_uuid
     self.uuid ||= SecureRandom.uuid
  end

  def active_superuser?
    self.active && self.superuser
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :draft_and_admin?

  def index
    @post = Post.last
  end

  def update
    @post = Post.new
    @post.body = params[:body]
    @post.save
    redirect_to root_path
  end

  def show

  end

  def login

  end

  protected

  def draft_and_admin?
    redirect_to login_path, :flash => { :error => "access_denied"} unless session[:admin] == true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :require_login

  private

  def require_login
    unless session[:admin]
      redirect_to root_path
    end
  end

end

app/controllers/frontpage_controller.rb
class FrontpageController < ApplicationController
  skip_before_filter :require_login

  def index
    @post = Post.last


  end
end

app/controllers/music_controller.rb
class MusicController < ApplicationController
  def index
  end

  def upload
  end

  def delete
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
  end

  def show
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :require_login

  def index
    @user = User.new
  end

  def create
    @user = User.find_by_username(params[:username].downcase)

    if !@user.nil? && @user.password == params[:password]
      session[:user_id] = @user.id
      session[:admin] = true
      redirect_to admin_path# if @user.superuser
      # TODO: redirect somewhere if they are in active admin
      #
      # TODO: make a special false clause for inactive members
      #
      # redirect somewhere else if we decide to have non admin routes
      # in the future
    else
      redirect_to login_path, :flash => { :error => "auth_fail" } and return
    end


  end

  def auth_fail
    # TODO make a page for users trying to break in

  end

  def destroy
   session[:user_id] = nil
    reset_session
    redirect_to root_path
  end

end

app/controllers/titles_controller.rb
class TitlesController < ApplicationController
  def new
    @title = Title.new
  end

  def show
  end

  def edit
  end

  def create
    @title = Title.new
    @title.name = params[:name]
    @title.order = params[:order]
    @title.visible = params[:visible]

    binding.pry
    if @title.save
      redirect_to admin_path and return
    else
      render 'new'
    end
  end

  def update
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login

  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.username = params[:user][:username]
    @user.password = params[:user][:password]
    @user.email_address = params[:user][:email_address]
    @user.save!

    UserMailer.new_user_request(@user).deliver

    # TODO - redirect to a page that says you will be waiting for admin approval
    redirect_to root_path
  end

  def superuser_dashboard
    @users = User.all
  end

end

app/helpers/admin_controller_helper.rb
module AdminControllerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def this_user_id
    session[:user_id]
  end

  def this_user
    return nil if this_user_id.nil?

    @this_user ||= User.find(this_user_id)
  end

end

app/helpers/frontpage_helper.rb
module FrontpageHelper
end

app/helpers/music_helper.rb
module MusicHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/titles_helper.rb
module TitlesHelper
end

app/views/admin/index.html.erb
<div class="admin-header">
  Admin control panel
</div>

<div class="admin-input">
  <div class="current-text">
    Current text:
  </div>

  <div>
    <%= @blog.billboard_text.gsub(/\n/, '<br />').html_safe unless @blog.nil? %>
    <%= "Empty" if @blog.nil? %>
  </div>

  <div class="admin-new-text">
    New text:
  </div>

  <div>
    <%= form_tag (blog_path) do %>

    <div>
      <%= text_area_tag 'body', nil, :rows => 10, :cols => 39 %>
    </div>

    <div class="admin-submit">
      <%= submit_tag 'Update text', :class => "submit-btn" %>
    </div>
    <% end %>
  </div>

  <div class="admin-logout">
    <%= link_to 'logout of admin page', logout_path, :class => "logout-btn" %>
  </div>
</div>

app/views/admin/title_edit.html.erb
<h1>Titles#edit</h1>
<p>Find me in app/views/titles/edit.html.erb</p>

app/views/admin/title_new.html.erb
<div class="admin_header_container">
  <div class="text_left admin-panel group">
    <span class="admin_header_text">Administrator control panel</span>
  </div>
  <div class="text_right admin-panel admin_panel_button_container group">
    <%= link_to 'LOGOUT', logout_path, :class => "admin_header_button" %>
  </div>
  <div class="clear"></div>
</div>

<div class="admin_body_container">

  <div class="admin_control_panel_flash_message_container">
    <!-- IF FLASH MAKE A MESSAGE HERE -->

  </div>

  <div class="admin_control_panel_dashboard_container">
   <div class="admin_control_panel_title_container">
      <span class="admin_control_panel_text">Add a new headline</span>
    </div>
  </div>

  <div class="admin_control_panel_form_container">
    <%= form_for @title, url: title_new_path(@title) do |t| %>

      <div class="admin_form_field_container">
        <%= t.label :name %>
        <%= t.text_field :name %>
      </div>

      <div class="admin_form_field_container">
        <%= t.label :order, "Priority" %>
        <%= t.number_field :order %>
      </div>

      <div class="admin_form_field_container">
        <%= t.label :visible %>
        <%= t.check_box :visible %>
      </div>

      <%= t.submit "SUBMIT NEW TITLE" %>
    <% end %>


  </div>

</div>

app/views/admin/title_show.html.erb
<h1>Titles#show</h1>
<p>Find me in app/views/titles/show.html.erb</p>

app/views/frontpage/_bio_copy.html.erb
<div class="listen-song-text">
    <p>
It’s going to take more than the space provided here to sum up the ideas and talent of NYC’s Xander Duell, who has fused decades’ worth of nuance into these thirteen songs. The implication in the title of this one is at least somewhat correct in that the experimental nature of Duell’s music rears its head in style and content atop songwriting that touches the emotional core without hesitation or regret. There is joy and sadness here, electronics and guitars, grandeur alongside the neon-lit sleaze. Calibrate your expectations appropriately on this one, but be prepared to have them shattered by this outsider work, in the spirit of Scott Walker’s numbered albums and the prime cut of ‘70s soft rock.
    </p>
  </span>

  <span class="wade_text">
  <p>
    Xander Duell exists in a parallel universe.  Experimental Tapes: Volume 2, released in 2011 on Mexican Summer, was a bit too much for most people to wrap their heads around.
  </p>

  <p>
    Though the record was far from being high-profile, it did attract a disparate array of musician fans.
  </p>

  <p>
    For his follow-up full-length, Wade Laiste, Xander was able to bring together the unlikely musical pairing of producers Andrew Wyatt of pop behemoths Miike Snow, and Damon McMahon, the voice behind Brooklyn’s Amen Dunes.
  </p>

  <p>
    Recorded in Sear Sound, one of New York City’s most renowned and historic recording studios, with a hyper-real rhythm section composed of David Bowie’s drummer (Sterling Campbell) and Maxwell’s bassist (Hod David), as well as musical accompaniment by producers Andrew Wyatt and Damon McMahon, the result is a surrealist medicated daydream coasting along the deepest and most immaculately precise grooves. Where Experimental Tapes: Volume 2 was raw and inward bedroom-pop, Wade Laiste is slick and extroverted future soul.
  </p>

  <p>
    It’s David Lynch blues & pill-head 2013 Avant-soul born from some of the deepest and most unusually combined musicianship on any record to come out of New York City for quite some time.
  </p>
</div>

app/views/frontpage/_music_box.html.erb
<div class="music_box_container"> 
  
  <div class="modal-close-btn music-modal-close-btn">X</div>

  <div class="axis-cover-crop"></div>

  <!-- soundcloud player -->
  <div class="soundcloud-player-container view-music left-container">
    <iframe width="305px" height="370" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/44456657&amp;color=000000&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"></iframe>
  </div><!-- .soundcloud-player-container -->

  <div class="itunes-link-container left-container">
    <a href="https://itunes.apple.com/us/album/earth-on-its-axis-single/id888363416?uo=4" target="itunes_store" style="display:inline-block;overflow:hidden;background:url(https://linkmaker.itunes.apple.com/htmlResources/assets/en_us//images/web/linkmaker/badge_itunes-lrg.png) no-repeat;width:110px;height:40px;@media only screen{background-image:url(https://linkmaker.itunes.apple.com/htmlResources/assets/en_us//images/web/linkmaker/badge_itunes-lrg.svg);}"></a>
  </div> 

  <!-- <div class="left-container">
    <%#= render 'bio_copy' %>
  </div>
 -->
  <div class="clear"></div>


</div><!-- .music_box_container -->

app/views/frontpage/_news_box.html.erb
     
<div class="front_page_text_space_hidden">&nbsp;</div>

<div id="front_page_text" class = "front_page_container">
  <div class="front_text">
    <span class="highlight">Xander Duell.</span> Composer. Performer.
  </div>

  <% unless @post.blank? || @post.body == "" %>
    <div class="frontpage_posts">
      <div class="frontpage_title_container">
        <span class="frontpage_post_text"><%= simple_format(@post.body) %></span>
      </div>
    </div><!-- .frontpage_posts -->
  <% else %>
    <div class="frontpage_title_container titles_empty_container">
      <span class="frontpage_post_text"><span class="titles_empty_post_body_text highlight_text">Come back soon</span>, news, tour dates and more are on their way.</span>
    </div>
  <% end %>

  <div class="social_container">
    <a href="https://www.facebook.com/pages/Xander-Duell/128971710446707"><span class="sprite_facebook"></span></a>
    <a href="https://twitter.com/xanderduell"><span class='sprite_twitter'></span></a>
    <a href="http://instagram.com/xanderduell"><span class="sprite_instagram"></span></a>

    <a href="https://itunes.apple.com/us/album/earth-on-its-axis-single/id888363416?uo=4" target="itunes_store" style="display:inline-block;overflow:hidden;background:url(https://linkmaker.itunes.apple.com/htmlResources/assets/en_us//images/web/linkmaker/badge_itunes-lrg.png) no-repeat;width:110px;height:40px;@media only screen{background-image:url(https://linkmaker.itunes.apple.com/htmlResources/assets/en_us//images/web/linkmaker/badge_itunes-lrg.svg);}" class="frontpage_itunes_link"></a>

  </div>

  <div class="frontpage_post_body_text contact_text_container">
    contact: <a href="mailto:xanderduell@gmail.com" target="_top">xanderduell@gmail.com</a>
  </div>
</div> 

app/views/frontpage/_video_box.html.erb
<div class="video_box_container"> 

  <div class="modal-close-btn video-modal-close-btn">X</div>

  <video id=home_video controls preload=auto width=814 height=360
poster="http://d25ai0wjxwz195.cloudfront.net/eoia_cover.png" data-setup="{}">
<source src="http://d25ai0wjxwz195.cloudfront.net/eoia.mp4" type='video/mp4'/>
</video>

</div><!-- .video_box_container -->

app/views/frontpage/index.html.erb
<div class="modal-background-overlay"></div>

<div class="wrapper">
  <div id="wrapper_nav">
    <div class="logo_container">
      <h1>XANDER DUELL</h1>
    </div><!-- .title -->
    <div class="menu">
      <nav>
        <ul>
          <li><a href="#" id="video" class="top_menu underline">EARTH ON ITS AXIS</a></li>
          <li><a href="#" id="music" class="top_menu underline">MUSIC</a></li>
        </ul>
      </nav>
    </div><!-- .menu -->
  </div><!-- #wrapper_nav -->

  <div id="music_container">
    <%= render 'music_box' %>
  </div> <!-- #music_container -->

  <div id="video_container">
    <%= render 'video_box' %>
  </div> <!-- #video_container -->

  <div id="container">
    <div class="image-1"></div>

    <div class="container-pad">
      &nbsp;
    </div>

    <%= render 'news_box' %>

    <div class="image2"></div>

    <div class="image-3"></div>

    <div class="clear"></div><!-- .clear -->

    <div class="container-pad">
        &nbsp;
    </div>
  </div><!-- #container -->

  <footer>
    <span class="footer-highlight">COPYRIGHT <%= Time.zone.now.year %>. XANDERDUELL.COM</span>
  </footer>
</div><!-- #wrapper -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>:: XANDER DUELL ::</title>
    <meta name="description" content="The Official Website for Musician, Composer Xander Duell">
    <%= stylesheet_link_tag   "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "//use.typekit.net/flt4gqz.js" %>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
    <%= csrf_meta_tags %>
    <link rel="shortcut icon" href="/favicon.ico" />
    <%#= favicon_link_tag %>
    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
</head>
<body>
    <div class="main_container">
        <%= yield %>
    </div>
</body>
</html>

<!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
<script>
    // var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
    // (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    // g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    // s.parentNode.insertBefore(g,s)}(document,'script'));
</script>

app/views/music/index.html.erb
<h1>Music#index</h1>
<p>Find me in app/views/music/index.html.erb</p>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/users/new.html.erb
<div class="admin-header">
  Admin control panel :: Create a new admin
</div>

<div class="new_admin_input_container">

  <div class="users_new_user_input_fields_container">
  <%= form_for :user do |f| %>
    <div>
      <%= flash[:message] if flash[:message] %>
    </div>

    <div>
      <%= f.label :username %> <br />
      <%= f.text_field :username %>
    </div>

    <div>
      <%= f.label :password %> <br />
      <%= f.password_field :password %>
    </div>

    <div>
      <%= f.label :email_address %> <br />
      <%= f.text_field :email_address %>
    </div>

  </div>

  <div class="admin-submit">
    <%= submit_tag 'SUBMIT', :class => "button" %>
  </div>

  <% end %>
  <div class="admin-logout">
    <%= link_to 'HOME', root_path, :class => "button" %>
  </div>

</div>